<!doctype html>
<html lang="gb">
<head>
	<title>Yeovill Youth Theatre</title>
	<meta name ="author" content="Matthew Barnett">
	<meta name ="generated by" content="me">
	<meta name ="description" content="This is Project 1, a brief introduction to HTML and CSS.">
	<meta name ="keywords" content="html, css, web design, bath, bath college">
	<meta name ="charset" content="utf-8">
	<link rel= "stylesheet" href= "css/styles.css" type= "text/css">
	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

	<!-- Jquery start -->

	<link rel="stylesheet" href="css/styles.css" type="text/css">
  <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

	<!-- Jquery end -->

	<!-- Facebook Javascript SDK start -->
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.6";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

	<!-- Facebook Javascript SDK end -->

</head>
<body>
	<?php
	include 'testing.php'
	?>																									<!--temporary links at the top of the page to reduce clutter in the main page-->
	<div id="header">
		<a href="index.php">
		<img src="assets/long logo.png"></img>
		</a>
	</div>

	<div id="menu">
		<?php	include 'navmenu.php'?>											<!--inserted code from the php page, navmenu.php-->
	</div>

	<div id="currentProductions">
		<!-- start slipsum code -->

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac magna non </p>

<!-- end slipsum code -->

	<!-- ABOUT 15 WORDs FIT HERE -->
	</div>

<div id="contactUsBox">

	<h1>You can reach us at:</h1>

	<br><br>

	<div><a href="mailto:sampleaddress@example.com"
	style="background-color:#556270;border:1px solid #1e3650;border-radius:4px;color:#ffffff;display:inline-block;font-family:sans-serif;font-size:13px;font-weight:bold;line-height:24px;text-align:center;text-decoration:none;width:137px;-webkit-text-size-adjust:none;mso-hide:all;">Email</a></div>
<!-- Source of email button: https://buttons.cm/  -->
<!--/////////////////////THIS IS A TEMPORARY EMAIL/////////////////////////////////-->
	<br>


	<div class="fb-like" data-href="https://www.facebook.com/YeovilYouthTheatre" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>

	<br><br>
	<a href="https://twitter.com/yytheatre" class="twitter-follow-button" data-show-count="false">Follow @yytheatre</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

	<br><br>

	<style>.ig-b- { display: inline-block; }
	.ig-b- img { visibility: hidden; }
	.ig-b-:hover { background-position: 0 -60px; } .ig-b-:active { background-position: 0 -120px; }
	.ig-b-v-24 { width: 137px; height: 24px; background: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24.png) no-repeat 0 0; }
	@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
	.ig-b-v-24 { background-image: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24@2x.png); background-size: 160px 178px; } }</style>
	<a href="https://www.instagram.com/yytheatre/?ref=badge" class="ig-b- ig-b-v-24"><img src="//badges.instagram.com/static/images/ig-badge-view-24.png" alt="Instagram" /></a>
</div>

<div id="ourSponsers">
<?php
	include 'sponserBanner.php'
?>
	<div>
</body>
</html>
