<!doctype html>
<html lang="gb">
<head>
	<title>Yeovill Youth Theatre</title>
	<meta name ="author" content="Matthew Barnett">
	<meta name ="generated by" content="me">
	<meta name ="description" content="This is Project 1, a brief introduction to HTML and CSS.">
	<meta name ="keywords" content="html, css, web design, bath, bath college">
	<meta name ="charset" content="utf-8">
	<link rel= "stylesheet" href= "css/styles.css" type= "text/css">
	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

	<!-- Jquery start -->

	<link rel="stylesheet" href="css/styles.css" type="text/css">
  <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

	<!-- Jquery end -->
</head>
<body>
	<div id="header">
		<img src="assets/long logo.png"></img>
	</div>

	<div id="menu">
		<?php	include 'navmenu.php'?>
	</div>

	<div id="currentProductions">
		<!-- start slipsum code -->

<p>Well, the way they make shows is, they make one show. That show's called a pilot.</p>

<!-- end slipsum code -->

	<!-- ABOUT 15 WORD FIT HERE -->
	</div>

	<div id ="imageAndTextWrapper">
		<div id="currentText">
		<h2>What is “current production name”</h2>
		<p><!-- start slipsum code -->

Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass.

				<!-- end slipsum code -->
</p>
		<h2>Information about “current production name”</h2>
		<p><!-- start slipsum code -->

Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass.

				<!-- end slipsum code -->
</p>

		</div>
		<div id="currentImageBox">
			<img src="assets/Seussical poster.jpg" id="currentImage"></img>
		</div>
	</div>

<div id="ourSponsers">
<?php
	include 'sponserBanner.php'
?>
	<div>
</body>
</html>
