<!doctype html>
<html lang="gb">
<head>
	<title>Yeovill Youth Theatre</title>
	<meta name ="author" content="Matthew Barnett">
	<meta name ="generated by" content="me">
	<meta name ="description" content="This is Project 1, a brief introduction to HTML and CSS.">
	<meta name ="keywords" content="html, css, web design, bath, bath college">
	<meta name ="charset" content="utf-8">
	<link rel= "stylesheet" href= "css/styles.css" type= "text/css">
	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

	<!-- Jquery start -->

	<link rel="stylesheet" href="css/styles.css" type="text/css">
  <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

	<!-- Jquery end -->
</head>
<body>
	<?php
	include 'testing.php'
	?>																											<!--temporary links at the top of the page to reduce clutter in the main page-->
	<div id="header">
		<a href="index.php">
		<img src="assets/long logo.png"></img>
	</a>
	</div>

	<div id="menu">
		<?php	include 'navmenu.php'?>													<!--inserted code from the php page, navmenu.php-->
	</div>

	<div id="currentProductions">
		<!-- start slipsum code -->

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac magna non </p>

<!-- end slipsum code -->

	<!-- ABOUT 15 WORD FIT HERE -->
	</div>

	<div id ="imageAndTextWrapper">
		<div id="currentText">
		<h2>What is “current production name”</h2>
		<p><!-- start slipsum code -->


			Proin ut quam eros. Donec sed lobortis diam. Nulla nec odio lacus. Quisque porttitor egestas dolor in placerat. Nunc vehicula dapibus ipsum. Duis venenatis risus non nunc fermentum dapibus. Nunc vehicula dapibus ipsum. Duis venenatis risus non nunc fermentum dapibus. Nunc vehicula dapibus ipsum. Duis venenatis risus non nunc fermentum dapibus.
				<!-- end slipsum code -->
</p>
		<h2>Information about “current production name”</h2>
		<p><!-- start slipsum code -->


			Proin ut quam eros. Donec sed lobortis diam. Nulla nec odio lacus. Quisque porttitor egestas dolor in placerat. Nunc vehicula dapibus ipsum. Duis venenatis risus non nunc fermentum dapibus. Nunc vehicula dapibus ipsum. Duis venenatis risus non nunc fermentum dapibus. Nunc vehicula dapibus ipsum. Duis venenatis risus non nunc fermentum dapibus.

				<!-- end slipsum code -->
</p>

		</div>
		<div id="currentImageBox">
			<img src="assets/Seussical poster.jpg" id="currentImage"></img>
		</div>
	</div>

<div id="ourSponsers">
<?php
	include 'sponserBanner.php'
?>
	<div>
</body>
</html>
