<!doctype html>
<html lang="gb">
<head>
	<title>Yeovill Youth Theatre</title>
	<meta name ="author" content="Matthew Barnett">
	<meta name ="generated by" content="me">
	<meta name ="description" content="This is Project 1, a brief introduction to HTML and CSS.">
	<meta name ="keywords" content="html, css, web design, bath, bath college">
	<meta name ="charset" content="utf-8">
	<link rel= "stylesheet" href= "css/styles.css" type= "text/css">
	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

	<!-- Jquery start -->

	<link rel="stylesheet" href="css/styles.css" type="text/css">
  <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

	<!-- Jquery end -->

<script>
	//JQuery slideshow start

	  $('document').ready(function(){

	    setInterval(function() {
	      var imageObject = $('#slideshowImage');
	      var imagePosition = imageObject.css('left');

	      if(imagePosition == "0px"){									//detects if the image is at the start position
	        imageObject.animate({left: '-380px'});		//sets how many pixels the image will move

	      }else if(imagePosition == "-380px"){				//repeats above and following commands until one of the start positions is found
	        imageObject.animate({left: '-760px'});

	      }else if (imagePosition == "-760px"){
	        imageObject.animate({left: '-1140px'});

	      }else{
	        imageObject.animate({left: '0px'});

	      }
	    }, 1500);																			//sets the delay (in milliseconds) before the function is looped again
	  });

	  //JQuery slideshow end
</script>


</head>
<body>
	<?php
	include 'testing.php'
	?>																									<!--temporary links at the top of the page to reduce clutter in the main page-->
	<div id="header">
		<a href="index.php">
		<img src="assets/long logo.png"></img>
		</a>
	</div>

	<div id="menu">
		<?php	include 'navmenu.php'?>											<!--inserted code from the php page, navmenu.php-->
	</div>

	<div id="currentProductions">
		<!-- start slipsum code -->

<p>Well, the way they make shows is, they make one show. That show's called a pilot.</p>

<!-- end slipsum code -->

	<!-- ABOUT 15 WORDs FIT HERE -->
	</div>

<div id="mainSlideShow">
	<div id="slideshowBox">
	<img src="assets/test full.png" id="slideshowImage"></img>
	<!--  PUT MARGIN AROUND SLIDESHOW	-->
	</div>
</div>
<div id="buttonWrapper">
	<div id="buttonOne">
		<a href="currentProduction.HTML">
		<img class="button"></img>
	</a>
	</div>
	<div id="buttonTwo">
		<a href="joiningUs.HTML">
		<img class="button"></img>
		</a>
	</div>
	<div id="buttonThree">
		<a href="fundraisers.HTML">
		<img class="button"></img>
		</a>
	</div>
	<div id="buttonFour">
		<a href="sponsors.HTML">
		<img class="button"></img>
		</a>
	</div>
</div>

<div id="aboutUs">
	<h1>Welcome to Yeovil youth theatre</h1>
	<p>Proin suscipit luctus orci placerat fringilla. Donec hendrerit laoreet risus eget adipiscing. Suspendisse in urna ligula, a volutpat mauris. Sed enim mi, bibendum eu pulvinar vel, sodales vitae dui. Pellentesque sed sapien lorem, at lacinia urna. In hac habitasse platea dictumst. Vivamus vel justo in leo laoreet ullamcorper non vitae lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin bibendum ullamcorper rutrum.</p>
</div>
<div id="ourSponsers">
<?php
	include 'sponserBanner.php'
?>
	<div>
</body>
</html>
