<!doctype html>
<html lang="gb">
<head>
	<title>Yeovill Youth Theatre</title>
	<meta name ="author" content="Matthew Barnett">
	<meta name ="generated by" content="me">
	<meta name ="description" content="This is Project 1, a brief introduction to HTML and CSS.">
	<meta name ="keywords" content="html, css, web design, bath, bath college">
	<meta name ="charset" content="utf-8">
	<link rel= "stylesheet" href= "css/styles.css" type= "text/css">
</head>
<body>
	<div id="header"></div>

	<div id="menu">
		<?php	include 'navmenu.php'?>
	</div>

<div id="mainSlideShow"></div>
<div id="buttonWrapper">
	<div id="buttonOne"></div>
	<div id="buttonTwo"></div>
	<div id="buttonThree"></div>
	<div id="buttonFour"></div>
</div>
<div id="aboutUs"></div>
<div id="ourSponsers"><div>
</body>
</html>
