<!doctype html>
<html lang="gb">
<head>
	<title>Yeovill Youth Theatre</title>
	<meta name ="author" content="Matthew Barnett">
	<meta name ="generated by" content="me">
	<meta name ="description" content="This is Project 1, a brief introduction to HTML and CSS.">
	<meta name ="keywords" content="html, css, web design, bath, bath college">
	<meta name ="charset" content="utf-8">
	<link rel= "stylesheet" href= "css/styles.css" type= "text/css">
	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

	<!-- Jquery start -->

	<link rel="stylesheet" href="css/styles.css" type="text/css">
  <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

	<!-- Jquery end -->

</head>
<body>
	<?php
	include 'testing.php'
	?>
	<div id="header">
		<img src="assets/long logo.png"></img>
	</div>

	<div id="menu">
		<?php	include 'navmenu.php'?>
	</div>

	<div id="currentProductions">
		<!-- start slipsum code -->

<p>Well, the way they make shows is, they make one show. That show's called a pilot.</p>

<!-- end slipsum code -->

	<!-- ABOUT 15 WORD FIT HERE -->
	</div>
	<div id="imageAndTextWrapper">
			<div id="whoAreWeText">
				<!-- start slipsum code -->

<p>
Proin ut quam eros. Donec sed lobortis diam. Nulla nec odio lacus. Quisque porttitor egestas dolor in placerat. Nunc vehicula dapibus ipsum. Duis venenatis risus non nunc fermentum dapibus. Morbi lorem ante, malesuada in mollis nec, auctor nec massa. Aenean tempus dui eget felis blandit at fringilla urna ultrices. Suspendisse feugiat, ante et viverra lacinia, lectus sem lobortis dui, ultricies consectetur leo mauris at tortor. Nunc et tortor sit amet orci consequat semper. Nulla non fringilla diam.  </p>

<p>
Proin ut quam eros. Donec sed lobortis diam. Nulla nec odio lacus. Quisque porttitor egestas dolor in placerat. Nunc vehicula dapibus ipsum. Duis venenatis risus non nunc fermentum dapibus. Morbi lorem ante, malesuada in mollis nec, auctor nec massa. Aenean tempus dui eget felis blandit at fringilla urna ultrices. Suspendisse feugiat, ante et viverra lacinia, lectus sem lobortis dui, ultricies consectetur leo mauris at tortor. Nunc et tortor sit amet orci consequat semper. Nulla non fringilla diam. </p>


<!-- end slipsum code -->
			</div>
			<div id="whoWeAreImageBox">
				<img src="assets/placeholder.jpg" id="whoWeAreImage"></img>
			</div>
	</div>
<div id="ourSponsers">
<?php
	include 'sponserBanner.php'
?>
	<div>
</body>
</html>
