<!doctype html>
<html lang="gb">
<head>
	<title>Yeovill Youth Theatre</title>
	<meta name ="author" content="Matthew Barnett">
	<meta name ="generated by" content="me">
	<meta name ="description" content="This is Project 1, a brief introduction to HTML and CSS.">
	<meta name ="keywords" content="html, css, web design, bath, bath college">
	<meta name ="charset" content="utf-8">
	<link rel= "stylesheet" href= "css/styles.css" type= "text/css">
	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

	<!-- Jquery start -->

	<link rel="stylesheet" href="css/styles.css" type="text/css">
  <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

	<!-- Jquery end -->

</head>
<body>
	<div id="header">
		<img src="assets/long logo.png"></img>
	</div>

	<div id="menu">
		<?php	include 'navmenu.php'?>
	</div>

	<div id="currentProductions">
		<!-- start slipsum code -->

<p>Well, the way they make shows is, they make one show. That show's called a pilot.</p>

<!-- end slipsum code -->

	<!-- ABOUT 15 WORD FIT HERE -->
	</div>
	<div id="imageAndTextWrapper">
			<div id="whoAreWeText">
				<!-- start slipsum code -->

<p>You see? It's curious. Ted did figure it out - time travel. And when we get back, we gonna tell everyone. How it's possible, how it's done, what the dangers are. But then why fifty years in the future when the spacecraft encounters a black hole does the computer call it an 'unknown entry event'? Why don't they know? If they don't know, that means we never told anyone. And if we never told anyone it means we never made it back. Hence we die down here. Just as a matter of deductive logic. </p>

<p>Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb. Hello there this is a test to add on some more words to the web page. I only need ten more words so hopefully this is enough </p>


<!-- end slipsum code -->
			</div>
			<div id="whoWeAreImageBox">
				<img src="assets/placeholder.jpg" id="whoWeAreImage"></img>
			</div>
	</div>
<div id="ourSponsers">
<?php
	include 'sponserBanner.php'
?>
	<div>
</body>
</html>
